name: deploy

on:
  push:
    branches:
      - master

jobs:
  caprover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u gleich --password-stdin
          docker build -t ghcr.io/gleich/terminal .
          docker push ghcr.io/gleich/terminal
      - uses: caprover/deploy-from-github@v1.1.2
        with:
          server: https://dev.mattglei.ch
          app: terminal
          token: '${{ secrets.CAPROVER_APP_TOKEN }}'
          image: ghcr.io/gleich/ssh
