name: deploy

on:
  push:
    branches:
      - master

jobs:
  caprover:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build & Push Image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u Matt-Gleich --password-stdin
          docker build -f docker/prod.Dockerfile -t ghcr.io/matt-gleich/ssh_me .
          docker push ghcr.io/matt-gleich/ssh_me
      - name: Deploy to Caprover
        run: docker run caprover/cli-caprover:v2.1.1 caprover deploy --caproverUrl https://api.mattglei.ch --caproverPassword ${{ secrets.CAPROVER_PASSWORD }} --caproverApp ssh --imageName ghcr.io/matt-gleich/ssh_me
